# 菌の保持期間
cootiesTick: 300

bangPlayer: POne0301
barrierPlayer: POne0301
buriPlayer: POne0301
confusionPlayer: POne0301
gazePlayer: POne0301
gazeTargetPlayer: POne0301
kickPlayer: POne0301
nyaPlayer: POne0301