# 菌の保持期間
cootiesTick: 1200

bangPlayer: kono_a
barrierPlayer: S4kiGake
buriPlayer: Nagatuki
confusionPlayer: imo64
gazePlayer: YOSHIKO__CHAN__
gazeTargetPlayer: roadhog_kun
kickPlayer: rnojaja
nyaPlayer: Yanyaa